name: CI

on:
  push:
  pull_request:

jobs:
  Compile:
    name: Compile (PHP '8.0')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - run: composer install
      - run: php compile.php
